trigger: none

stages:
- stage: Run1ESTestStage
  jobs:
  - job: Run1ESTestJob
    pool:
      name: NetCore1ESPool-Svc-Internal-PR17463
      demands: ImageOverride -equals Build.Server.Amd64.VS2017-PR17463
    steps:
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: Write-Host test
      displayName: Run script
