trigger: none

stages:
- stage: Run1ESTestStage
  jobs:
  - job: Test1ES
    pool:
      name: NetCore1ESPool-Svc-Internal
      demands: ImageOverride -equals Build.Windows.10.Amd64.VS2017
    steps:
    - task: MicroBuildSigningPlugin@2
      displayName: Install MicroBuild plugin
      inputs:
        signType: real
        zipSources: false
        feedSource: https://dnceng.pkgs.visualstudio.com/_packaging/MicroBuildToolset/nuget/v3/index.json
      env:
        TeamName: DotNetCore
    - task: MicroBuildCleanup@1
      displayName: Execute Microbuild cleanup tasks
      env:
        TeamName: DotNetCore
