trigger: none

stages:
- stage: Run1ESTestStage
  jobs:
  - job: Test1ES
    pool:
      name: NetCore1ESPool-Svc-Public
      demands: ImageOverride -equals Build.Windows.10.Amd64.VS2017.Open
    steps:
    - powershell: Write-Host Test
